name: car_pooling_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.1.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    firebase_core: ^2.24.2
    firebase_auth: ^4.15.3
    google_sign_in: ^6.1.6
    shared_preferences: ^2.2.0
    http: ^1.1.0
    google_maps_flutter: ^2.5.0
    geolocator: ^10.1.0
    flutter_polyline_points: ^2.0.0
    sign_in_with_apple: ^5.0.0
    location: ^5.0.3
    intl: ^0.19.0
    logger: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_native_splash: ^2.3.9
    flutter_launcher_icons: ^0.13.1

flutter:
    uses-material-design: true
    assets:
        - assets/images/image.png
        - assets/images/google_logo.png
        - assets/images/go_ride_logo.png

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/google_logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/google_logo.png"
    min_sdk_android: 21